### PR TITLE
Fix Server Issues

### PR DESCRIPTION
**Pull request by Trainfire**
I've rewrote the SteamQuery method that should fix the issues that were happening. It will also catch any errors and log it, as opposed to out right crashing.

### CODE REVIEW

**Comment by Fantasmos** [comment]
it was something regarding a discarded object not found, have you tested it at length under mono? It usually doesn't crash until 10 minutes

**Comment by Trainfire** [comment]
That was the error I was having, though it happened immediately after the first request and not 10 minutes in.

I have it running under Mono on my server now and it seems to be working fine for the most part. Occasionally there will be failed connection attempts, but it still continues to run. Maybe the send and receive time values need to be increased to account for long delays.

As an aside, the auto map-deletion functionality seems to be working fine now as well.

**Comment by Fantasmos** [comment]
Alright, thank you very much for this help. I'm going to upload the changes in a few hours and it should hopefully run without a hitch.

**Comment by Fantasmos** [comment]
I should've asked this before merge, Garbage collection is still working fine though right? Before Hand UDP connections weren't getting closed which just ate away at memory which is scarce

**Comment by Trainfire** [comment]
The Using statement will dispose the Client as soon as that code block has
finished, so it should be fine.

**Comment by Fantasmos** [comment]
Ah, that's heaps cool

**Comment by Fantasmos** [comment]
As of right now the bot will spam the mapname on every receive, disabled just the message part.

**Pull request merged**
